[1m========================================== test session starts ===========================================[0m
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0 -- /opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/bin/python3.13
cachedir: .pytest_cache
rootdir: /Users/abdulazizalmoafa/Documents/mlops/02/ex10-git/genre_classification/check_data
collected 4 items                                                                                        [0m[1m

test_data.py::test_column_presence_and_type [32mPASSED[0m
test_data.py::test_class_names [32mPASSED[0m
test_data.py::test_column_ranges [32mPASSED[0m
test_data.py::test_kolmogorov_smirnov [32mPASSED[0m

[33m============================================ warnings summary ============================================[0m
../../../../../../../../opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/lib/python3.13/site-packages/wandb/analytics/sentry.py:263
../../../../../../../../opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/lib/python3.13/site-packages/wandb/analytics/sentry.py:263
  /opt/anaconda3/envs/mlflow-4d13597ed0443924acacbd90bdc85c91cac87c1c/lib/python3.13/site-packages/wandb/analytics/sentry.py:263: DeprecationWarning: The `Scope.user` setter is deprecated in favor of `Scope.set_user()`.
    self.scope.user = {"email": email}

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[33m===================================== [32m4 passed[0m, [33m[1m2 warnings[0m[33m in 9.34s[0m[33m ======================================[0m
